In [1]:
import numpy as np

In [2]:
list1 = [0,1,2,3,4]
list1

[0, 1, 2, 3, 4]

In [3]:
arr1d = np.array(list1)
arr1d

array([0, 1, 2, 3, 4])

In [4]:
list1.append(5)

In [5]:
# arr1d.append(5) # Memory already allocated can't reallocate

In [6]:
# list1 + 2   # Error
arr1d + 2

array([2, 3, 4, 5, 6])

In [7]:
list2 = [[1,1,1],[2,2,2],[3,3,3]]
arr2d = np.array(list2)

In [8]:
type(arr2d)

numpy.ndarray

In [9]:
arr2d.dtype

dtype('int32')

In [10]:
arr2d = np.array(list2,dtype='float')

In [11]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [12]:
arr2d.astype('int')

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [13]:
arr2d.astype('str')

array([['1.0', '1.0', '1.0'],
       ['2.0', '2.0', '2.0'],
       ['3.0', '3.0', '3.0']], dtype='<U32')

In [14]:
arr2d  # because inplace was False

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [15]:
list1.append('6')
list1   # Heterogenous items allowed in list, numpy arrrays only support homogenous items

[0, 1, 2, 3, 4, 5, '6']

In [16]:
np2list = arr2d.tolist()
np2list

[[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]]

In [17]:
# Useful in client-server connections
arr2d.tostring()

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@'

In [18]:
arr2d.tobytes()

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@'

# dtype and Shape

In [19]:
list2

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [20]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [21]:
arr2d = arr2d.astype('float')
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [22]:
print('shape',arr1d.shape)
print('dtype',arr1d.dtype)
print('size',arr1d.size)
print('dimension',arr1d.ndim)

shape (5,)
dtype int32
size 5
dimension 1


In [23]:
print('shape',arr2d.shape)
print('dtype',arr2d.dtype)
print('size',arr2d.size)
print('dimension',arr2d.ndim)

shape (3, 3)
dtype float64
size 9
dimension 2


In [24]:
print(arr1d)
print()
print(arr2d)

[0 1 2 3 4]

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [25]:
arr1d = arr1d * arr1d

In [26]:
arr1d

array([ 0,  1,  4,  9, 16])

In [27]:
arr1d[1]

1

In [28]:
arr2d[1]

array([2., 2., 2.])

In [29]:
arr2d[0][0]

1.0

In [30]:
boolarr = arr2d < 3

In [31]:
boolarr

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [32]:
arr2d[boolarr]  # makes an array using the true-condition items

array([1., 1., 1., 2., 2., 2.])

In [33]:
# Reversing Rows
arr2d[::-1,]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [34]:
# Reversing Columns
arr2d[:,::-1]

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [35]:
# Reversing both
arr2d[::-1,::-1]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

## np.nan , np.inf

In [36]:
np.nan

nan

In [37]:
np.inf

inf

In [38]:
# Using nan and inf values 
arr2d[0][0] = np.nan 
arr2d[0][1] = np.inf
arr2d 

array([[nan, inf,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [39]:
np.isnan(arr2d)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [40]:
np.isinf(arr2d)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [41]:
missing_flag = np.isnan(arr2d) | np.isinf(arr2d)
missing_flag

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [42]:
# Replace inf and nan with 0

In [43]:
arr2d[missing_flag]

array([nan, inf])

In [44]:
arr2d[missing_flag] = 0

In [45]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

# Statistical Operations

In [46]:
# Mean , std, var

In [47]:
print(arr2d.mean())
# print(arr2d.median())
# print(arr2d.mode())
print(arr2d.std())
print(arr2d.max())
print(arr2d.min())

1.7777777777777777
1.1331154474650633
3.0
0.0


In [48]:
arr2d.squeeze()

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [49]:
arr2d.cumsum()

array([ 0.,  0.,  1.,  3.,  5.,  7., 10., 13., 16.])

In [50]:
arr = arr2d[:2,:2]
arr

array([[0., 0.],
       [2., 2.]])

In [51]:
arr2d[1:3,1:2]

array([[2.],
       [3.]])

In [52]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [53]:
# arr2d.reshape(3,4)  # not enough elements to cover 3 * 4 = 12 
arr2d.reshape(1,9)

array([[0., 0., 1., 2., 2., 2., 3., 3., 3.]])

In [54]:
arr2d.reshape(9,1)

array([[0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.]])

In [55]:
a = arr2d.flatten()  # to convert into single dimensional array
a  # copy

array([0., 0., 1., 2., 2., 2., 3., 3., 3.])

In [56]:
b = arr2d.ravel()  # to convert into single dimensional array
b # reference, thus memory-efficient

array([0., 0., 1., 2., 2., 2., 3., 3., 3.])

In [57]:
a[0] = -1
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [58]:
b[0] = -1
arr2d

array([[-1.,  0.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

# Sequence,Repitions and Random Numbers

In [59]:
np.arange(1,5,dtype='int')
# np.arange(1,5,dtype='float')
# np.arange(1,5,dtype='str')
# np.arange(1,5,dtype='object')

array([1, 2, 3, 4])

In [60]:
np.arange(1,50,2)  # Odd nos
# np.arange(2,50,2)  # Even nos

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [61]:
# Inserting linearly spaecd numbers between numbers 
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [62]:
# Inserting logarithmically spaecd numbers between numbers 
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [63]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [64]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [65]:
a = [1,2,3]
a

[1, 2, 3]

In [66]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [67]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [68]:
np.repeat(arr2d,3)

array([-1., -1., -1.,  0.,  0.,  0.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.])

In [69]:
np.repeat(arr2d,3).shape

(27,)

In [70]:
np.random.rand(3,3)  # uniformly distributed (0,1)

array([[0.22008009, 0.64153313, 0.03585856],
       [0.34092363, 0.23560165, 0.85592572],
       [0.84215434, 0.73063413, 0.77861593]])

In [71]:
np.random.randn(3,3)  # normally distributed (-1,1)

array([[ 0.20085905,  1.04299235,  0.8197348 ],
       [ 1.45136194, -0.00313677, -0.46253146],
       [-0.07440822, -0.88127775,  0.72837506]])

In [72]:
np.random.randint(0,10,[3,3])

array([[5, 5, 3],
       [0, 8, 8],
       [2, 8, 7]])

In [73]:
np.random.seed(0)
np.random.randint(0,10,[3,3])

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [74]:
np.random.seed(0)
np.random.randint(0,10,[3,3])

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [75]:
np.random.seed(1)
np.random.randint(0,10,[3,3])

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [76]:
np.unique(arr2d)

array([-1.,  0.,  1.,  2.,  3.])

In [77]:
arr2d

array([[-1.,  0.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [81]:
uniques,counts = np.unique(arr2d,return_counts=True)
for a,b in (zip(uniques,counts)):
    print(a,b)

-1.0 1
0.0 1
1.0 1
2.0 3
3.0 3
