In [1]:
import numpy as np

In [2]:
arr = np.array([8,94,8,56,1,3,4,5,7])
print(arr)

[ 8 94  8 56  1  3  4  5  7]


In [3]:
index_gt0 = np.where(arr>10)
index_gt0  # now we can get indexes as well

(array([1, 3], dtype=int32),)

In [4]:
arr[index_gt0]

array([94, 56])

In [5]:
arr[arr>10]

array([94, 56])

In [6]:
arr > 10 # Creates a boolean array

array([False,  True, False,  True, False, False, False, False, False])

In [7]:
np.where(arr>10,'gt10','lt10') # Prints result of condition on the array

array(['lt10', 'gt10', 'lt10', 'gt10', 'lt10', 'lt10', 'lt10', 'lt10',
       'lt10'], dtype='<U4')

In [8]:
arr.max()

94

In [9]:
arr.argmax()

1

In [10]:
arr.min()

1

In [11]:
arr.argmin()

4

In [12]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

# Read and Write Csv file
## np.genfromtxt() , np.loadtxt()

In [13]:
path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
data = np.genfromtxt(path,delimiter=',',skip_header=1,filling_values=-1000,dtype='float')

In [14]:
data

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [15]:
data.shape

(392, 9)

In [16]:
np.set_printoptions(suppress=True)  # Set scientific notation off
data[:3]

array([[   18. ,     8. ,   307. ,   130. ,  3504. ,    12. ,    70. ,
            1. , -1000. ],
       [   15. ,     8. ,   350. ,   165. ,  3693. ,    11.5,    70. ,
            1. , -1000. ],
       [   18. ,     8. ,   318. ,   150. ,  3436. ,    11. ,    70. ,
            1. , -1000. ]])

In [17]:
path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
data2 = np.genfromtxt(path,delimiter=',',skip_header=1,dtype=object)
data2[:4]

array([[b'18', b'8', b'307', b'130', b'3504', b'12', b'70', b'1',
        b'"chevrolet chevelle malibu"'],
       [b'15', b'8', b'350', b'165', b'3693', b'11.5', b'70', b'1',
        b'"buick skylark 320"'],
       [b'18', b'8', b'318', b'150', b'3436', b'11', b'70', b'1',
        b'"plymouth satellite"'],
       [b'16', b'8', b'304', b'150', b'3433', b'12', b'70', b'1',
        b'"amc rebel sst"']], dtype=object)

In [18]:
np.savetxt('data.csv',data,delimiter=',')

In [19]:
np.save('data.npy',data)

In [20]:
np.savez('data2.npz',data,data2)   # Storing in Numpy Zip Files

In [21]:
d = np.load('data.npy')
d

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [22]:
d2 = np.load('data2.npz')  # Retreving from Numpy Zip Files
d2.files

['arr_0', 'arr_1']

In [23]:
d2['arr_0']

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [25]:
# d2['arr_1']

# Concat with row and col wise 

In [27]:
arr1 = np.zeros([4,4])
arr2 = np.ones([4,4])

In [28]:
print(arr1)
print()
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
# np.concatenate, np.vstack and np.r_ give the same result
np.concatenate([arr1,arr2],axis=0)
np.vstack([arr1,arr2])
np.r_[arr1,arr2]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
# np.concatenate, np.hstack and np.c_ give the same result
np.concatenate([arr1,arr2],axis=1)
np.hstack([arr1,arr2])
np.c_[arr1,arr2]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

## Sort a Numpy Array

In [39]:
arr = np.random.randint(1,10,size=[10,5])
arr

array([[5, 6, 2, 9, 1],
       [3, 7, 1, 9, 6],
       [5, 8, 9, 6, 3],
       [3, 2, 8, 4, 6],
       [7, 5, 8, 4, 1],
       [1, 2, 6, 1, 2],
       [6, 8, 9, 7, 8],
       [1, 7, 1, 5, 3],
       [8, 9, 6, 2, 7],
       [4, 4, 3, 6, 3]])

In [40]:
np.sort(arr,axis=0) # Columnwise

array([[1, 2, 1, 1, 1],
       [1, 2, 1, 2, 1],
       [3, 4, 2, 4, 2],
       [3, 5, 3, 4, 3],
       [4, 6, 6, 5, 3],
       [5, 7, 6, 6, 3],
       [5, 7, 8, 6, 6],
       [6, 8, 8, 7, 6],
       [7, 8, 9, 9, 7],
       [8, 9, 9, 9, 8]])

In [41]:
np.sort(arr,axis=1) #Rowwise

array([[1, 2, 5, 6, 9],
       [1, 3, 6, 7, 9],
       [3, 5, 6, 8, 9],
       [2, 3, 4, 6, 8],
       [1, 4, 5, 7, 8],
       [1, 1, 2, 2, 6],
       [6, 7, 8, 8, 9],
       [1, 1, 3, 5, 7],
       [2, 6, 7, 8, 9],
       [3, 3, 4, 4, 6]])

In [43]:
# Keeping a Row intact
sorted_index = arr[:,0].argsort()

In [44]:
arr[sorted_index]

array([[1, 2, 6, 1, 2],
       [1, 7, 1, 5, 3],
       [3, 7, 1, 9, 6],
       [3, 2, 8, 4, 6],
       [4, 4, 3, 6, 3],
       [5, 6, 2, 9, 1],
       [5, 8, 9, 6, 3],
       [6, 8, 9, 7, 8],
       [7, 5, 8, 4, 1],
       [8, 9, 6, 2, 7]])

#  Working with Dates

In [45]:
d = np.datetime64('2019-06-02 23:10:00')
d

numpy.datetime64('2019-06-02T23:10:00')

In [46]:
d + 1000

numpy.datetime64('2019-06-02T23:26:40')

In [47]:
16*60 + 40

1000

In [48]:
oneday = np.timedelta64(1,'D')
oneday

numpy.timedelta64(1,'D')

In [49]:
d + oneday

numpy.datetime64('2019-06-03T23:10:00')

In [50]:
oneminute = np.timedelta64(1,'m')
oneminute

numpy.timedelta64(1,'m')

In [51]:
d + oneminute

numpy.datetime64('2019-06-02T23:11:00')

In [57]:
dates = np.arange(np.datetime64('2019-06-02'),np.datetime64('2020-06-02'),5)
dates

array(['2019-06-02', '2019-06-07', '2019-06-12', '2019-06-17',
       '2019-06-22', '2019-06-27', '2019-07-02', '2019-07-07',
       '2019-07-12', '2019-07-17', '2019-07-22', '2019-07-27',
       '2019-08-01', '2019-08-06', '2019-08-11', '2019-08-16',
       '2019-08-21', '2019-08-26', '2019-08-31', '2019-09-05',
       '2019-09-10', '2019-09-15', '2019-09-20', '2019-09-25',
       '2019-09-30', '2019-10-05', '2019-10-10', '2019-10-15',
       '2019-10-20', '2019-10-25', '2019-10-30', '2019-11-04',
       '2019-11-09', '2019-11-14', '2019-11-19', '2019-11-24',
       '2019-11-29', '2019-12-04', '2019-12-09', '2019-12-14',
       '2019-12-19', '2019-12-24', '2019-12-29', '2020-01-03',
       '2020-01-08', '2020-01-13', '2020-01-18', '2020-01-23',
       '2020-01-28', '2020-02-02', '2020-02-07', '2020-02-12',
       '2020-02-17', '2020-02-22', '2020-02-27', '2020-03-03',
       '2020-03-08', '2020-03-13', '2020-03-18', '2020-03-23',
       '2020-03-28', '2020-04-02', '2020-04-07', '2020-

# Numpy Advanced Functions

In [58]:
# Vectorize()

In [59]:
def foo(x):
    if x % 2 == 0:
        return x ** 2
    else:
        return x / 2
foo(10)

100

In [60]:
foo(11)

5.5

In [61]:
foo_v = np.vectorize(foo,otypes=[float])
print(arr)
print()
foo_v(arr)

[[5 6 2 9 1]
 [3 7 1 9 6]
 [5 8 9 6 3]
 [3 2 8 4 6]
 [7 5 8 4 1]
 [1 2 6 1 2]
 [6 8 9 7 8]
 [1 7 1 5 3]
 [8 9 6 2 7]
 [4 4 3 6 3]]



array([[ 2.5, 36. ,  4. ,  4.5,  0.5],
       [ 1.5,  3.5,  0.5,  4.5, 36. ],
       [ 2.5, 64. ,  4.5, 36. ,  1.5],
       [ 1.5,  4. , 64. , 16. , 36. ],
       [ 3.5,  2.5, 64. , 16. ,  0.5],
       [ 0.5,  4. , 36. ,  0.5,  4. ],
       [36. , 64. ,  4.5,  3.5, 64. ],
       [ 0.5,  3.5,  0.5,  2.5,  1.5],
       [64. ,  4.5, 36. ,  4. ,  3.5],
       [16. , 16. ,  1.5, 36. ,  1.5]])